#include "particles.h"
#include <stdio.h>

void vertical_test() {
	particle* p_p1 = nil_particle();
	(p_p1->position)[0] = 0.25;
	(p_p1->position)[1] = 0.25;
	(p_p1->velocity)[0] = 0.5;
	(p_p1->velocity)[1] = 0.0;
	p_p1->mass = 0.5;
	p_p1->radius = 0.01;
	particle* p_p2 = nil_particle();
	(p_p2->position)[0] = 0.25;
	(p_p2->position)[1] = 0.25;
	(p_p2->velocity)[0] = -0.5;
	(p_p2->velocity)[1] = 0.0;
	p_p2->mass = 0.5;
	p_p2->radius = 0.01;
	particle* p_p3 = nil_particle();
	(p_p3->position)[0] = 0.25;
	(p_p3->position)[1] = 0.25;
	(p_p3->velocity)[0] = 0.0;
	(p_p3->velocity)[1] = 0.5;
	p_p3->mass = 0.5;
	p_p3->radius = 0.01;
	particle* p_p4 = nil_particle();
	(p_p4->position)[0] = 0.25;
	(p_p4->position)[1] = 0.25;
	(p_p4->velocity)[0] = 0.0;
	(p_p4->velocity)[1] = -0.5;
	p_p4->mass = 0.5;
	p_p4->radius = 0.01;
	particle* p_p5 = nil_particle();
	(p_p5->position)[0] = 0.25;
	(p_p5->position)[1] = 0.25;
	(p_p5->velocity)[0] = 0.25;
	(p_p5->velocity)[1] = -0.4;
	p_p5->mass = 0.5;
	p_p5->radius = 0.01;
	double t_aux = t_v_wall_collision(p_p1);
	v_v_wall_collision_up(p_p1);
	printf("p1   v   %3lf  (%lf, %lf) \n", t_aux, (p_p1->velocity)[0], (p_p1->velocity)[1]);
	t_aux = t_v_wall_collision(p_p2);
	v_v_wall_collision_up(p_p2);
	printf("p2   v   %3lf  (%lf, %lf) \n", t_aux, (p_p2->velocity)[0], (p_p2->velocity)[1]);
	t_aux = t_v_wall_collision(p_p3);
	v_v_wall_collision_up(p_p3);
	printf("p3   v   %3lf  (%lf, %lf) \n", t_aux, (p_p3->velocity)[0], (p_p3->velocity)[1]);
	t_aux = t_v_wall_collision(p_p4);
	v_v_wall_collision_up(p_p4);
	printf("p4   v   %3lf  (%lf, %lf) \n", t_aux, (p_p4->velocity)[0], (p_p4->velocity)[1]);
	t_aux = t_v_wall_collision(p_p5);
	v_v_wall_collision_up(p_p5);
	printf("p5   v   %3lf  (%lf, %lf)\n", t_aux, (p_p5->velocity)[0], (p_p5->velocity)[1]);
	deallocate_particle(p_p1);
	deallocate_particle(p_p2);
	deallocate_particle(p_p3);
	deallocate_particle(p_p4);
	deallocate_particle(p_p5);
}

void horizontal_test() {
	particle* p_p1 = nil_particle();
	(p_p1->position)[0] = 0.25;
	(p_p1->position)[1] = 0.25;
	(p_p1->velocity)[0] = 0.5;
	(p_p1->velocity)[1] = 0.0;
	p_p1->mass = 0.5;
	p_p1->radius = 0.01;
	particle* p_p2 = nil_particle();
	(p_p2->position)[0] = 0.25;
	(p_p2->position)[1] = 0.25;
	(p_p2->velocity)[0] = -0.5;
	(p_p2->velocity)[1] = 0.0;
	p_p2->mass = 0.5;
	p_p2->radius = 0.01;
	particle* p_p3 = nil_particle();
	(p_p3->position)[0] = 0.25;
	(p_p3->position)[1] = 0.25;
	(p_p3->velocity)[0] = 0.0;
	(p_p3->velocity)[1] = 0.5;
	p_p3->mass = 0.5;
	p_p3->radius = 0.01;
	particle* p_p4 = nil_particle();
	(p_p4->position)[0] = 0.25;
	(p_p4->position)[1] = 0.25;
	(p_p4->velocity)[0] = 0.0;
	(p_p4->velocity)[1] = -0.5;
	p_p4->mass = 0.5;
	p_p4->radius = 0.01;
	particle* p_p5 = nil_particle();
	(p_p5->position)[0] = 0.25;
	(p_p5->position)[1] = 0.25;
	(p_p5->velocity)[0] = 0.25;
	(p_p5->velocity)[1] = -0.4;
	p_p5->mass = 0.5;
	p_p5->radius = 0.01;
	double t_aux = t_h_wall_collision(p_p1,0);
	v_h_wall_collision_up(p_p1);
	printf("p1   v   %3lf  (%lf, %lf) \n", t_aux, (p_p1->velocity)[0], (p_p1->velocity)[1]);
	t_aux = t_h_wall_collision(p_p2,0);
	v_h_wall_collision_up(p_p2);
	printf("p2   v   %3lf  (%lf, %lf) \n", t_aux, (p_p2->velocity)[0], (p_p2->velocity)[1]);
	t_aux = t_h_wall_collision(p_p3, 0);
	v_h_wall_collision_up(p_p3);
	printf("p3   v   %3lf  (%lf, %lf) \n", t_aux, (p_p3->velocity)[0], (p_p3->velocity)[1]);
	t_aux = t_h_wall_collision(p_p4,0);
	v_h_wall_collision_up(p_p4);
	printf("p4   v   %3lf  (%lf, %lf) \n", t_aux, (p_p4->velocity)[0], (p_p4->velocity)[1]);
	t_aux = t_h_wall_collision(p_p5,0);
	v_h_wall_collision_up(p_p5);
	printf("p5   v   %3lf  (%lf, %lf) \n", t_aux, (p_p5->velocity)[0], (p_p5->velocity)[1]);
	deallocate_particle(p_p1);
	deallocate_particle(p_p2);
	deallocate_particle(p_p3);
	deallocate_particle(p_p4);
	deallocate_particle(p_p5);
}

void collision_test() {
	particle* p_p1 = nil_particle();
	(p_p1->position)[0] = 0.25;
	(p_p1->position)[1] = 0.25;
	(p_p1->velocity)[0] = 0.5;
	(p_p1->velocity)[1] = 0.0;
	p_p1->mass = 0.5;
	p_p1->radius = 0.01;
	particle* p_p2 = nil_particle();
	(p_p2->position)[0] = 0.25;
	(p_p2->position)[1] = 0.25;
	(p_p2->velocity)[0] = -0.5;
	(p_p2->velocity)[1] = 0.0;
	p_p2->mass = 0.5;
	p_p2->radius = 0.01;
	particle* p_p3 = nil_particle();
	(p_p3->position)[0] = 0.25;
	(p_p3->position)[1] = 0.25;
	(p_p3->velocity)[0] = 0.0;
	(p_p3->velocity)[1] = 0.5;
	p_p3->mass = 0.5;
	p_p3->radius = 0.01;
	particle* p_p4 = nil_particle();
	(p_p4->position)[0] = 0.25;
	(p_p4->position)[1] = 0.25;
	(p_p4->velocity)[0] = 0.0;
	(p_p4->velocity)[1] = -0.5;
	p_p4->mass = 0.5;
	p_p4->radius = 0.01;
	particle* p_p5 = nil_particle();
	(p_p5->position)[0] = 0.25;
	(p_p5->position)[1] = 0.25;
	(p_p5->velocity)[0] = 0.25;
	(p_p5->velocity)[1] = -0.4;
	p_p5->mass = 0.5;
	p_p5->radius = 0.01;
	particle* p_p6 = nil_particle();
	(p_p6->position)[0] = 0.5;
	(p_p6->position)[1] = 0.25;
	(p_p6->velocity)[0] = 0.0;
	(p_p6->velocity)[1] = 0.0;
	p_p6->mass = 0.8;
	p_p6->radius = 0.005;
	particle* p_p7 = nil_particle();
	(p_p7->position)[0] = 0.75;
	(p_p7->position)[1] = 0.25;
	(p_p7->velocity)[0] = -0.25;
	(p_p7->velocity)[1] = 0.0;
	p_p7->mass = 0.5;
	p_p7->radius = 0.01;
	particle* p_p8 = nil_particle();
	(p_p8->position)[0] = 0.6;
	(p_p8->position)[1] = 0.8;
	(p_p8->velocity)[0] = 0.25;
	(p_p8->velocity)[1] = -0.4;
	p_p8->mass = 0.8;
	p_p8->radius = 0.005;
	double t_aux;
	//print_particle(p_p1);
	//print_particle(p_p6);
	t_aux = t_particle_collision(p_p1, p_p6);
	pos_up(p_p1, t_aux, 0);
	pos_up(p_p6, t_aux, 0);
	v_collision_up(p_p1, p_p6, 0);
	
	printf("p1   p6     %3lf  (%lf, %lf) (%lf, %lf) \n", t_aux, (p_p1->velocity)[0], (p_p1->velocity)[1], (p_p6->velocity)[0], (p_p6->velocity)[1]);
	(p_p1->position)[0] = 0.25;
	(p_p1->position)[1] = 0.25;
	(p_p1->velocity)[0] = 0.5;
	(p_p1->velocity)[1] = 0.0;
	t_aux = t_particle_collision(p_p1, p_p7);
	pos_up(p_p1, t_aux, 0);
	pos_up(p_p7, t_aux, 0);
	v_collision_up(p_p1, p_p7, 0);
	printf("p1   p7     %3lf  (%lf, %lf) (%lf, %lf) \n", t_aux, (p_p1->velocity)[0], (p_p1->velocity)[1], (p_p7->velocity)[0], (p_p7->velocity)[1]);
	(p_p1->position)[0] = 0.25;
	(p_p1->position)[1] = 0.25;
	(p_p1->velocity)[0] = 0.5;
	(p_p1->velocity)[1] = 0.0;
	t_aux = t_particle_collision(p_p1, p_p8);
	pos_up(p_p1, t_aux, 0);
	pos_up(p_p8, t_aux, 0);
	v_collision_up(p_p1, p_p8, 0);
	printf("p1   p8     %3lf  (%lf, %lf) (%lf, %lf) \n", t_aux, (p_p1->velocity)[0], (p_p1->velocity)[1], (p_p8->velocity)[0] ,(p_p8->velocity)[1]);
	(p_p7->position)[0] = 0.75;
	(p_p7->position)[1] = 0.25;
	(p_p7->velocity)[0] = -0.25;
	(p_p7->velocity)[1] = 0.0;
	(p_p8->position)[0] = 0.6;
	(p_p8->position)[1] = 0.8;
	(p_p8->velocity)[0] = 0.25;
	(p_p8->velocity)[1] = -0.4;
	t_aux = t_particle_collision(p_p7, p_p8);
	pos_up(p_p7, t_aux, 0);
	pos_up(p_p8, t_aux, 0);
	v_collision_up(p_p7, p_p8, 0);
	printf("p7   p8     %3lf  (%lf, %lf) (%lf, %lf) \n", t_aux, (p_p7->velocity)[0], (p_p7->velocity)[1], (p_p8->velocity)[0], (p_p8->velocity)[1]);
	deallocate_particle(p_p1);
	deallocate_particle(p_p2);
	deallocate_particle(p_p3);
	deallocate_particle(p_p4);
	deallocate_particle(p_p5);
	deallocate_particle(p_p6);
	deallocate_particle(p_p7);
	deallocate_particle(p_p8);
}


int main() { //Simple implementation of a test, could have been done more elegantly with a file loader
	printf("A | B | Time to collision | Velocities \n");
	vertical_test();
	horizontal_test();
	collision_test();
	return 0;
}
